version: '3'

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"  # Прокидываем порт 80 наружу
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./CatChatBackReborn
    environment:
      - MONGO_URI=mongodb://mongo:27017/chat
    ports:
      - "8000:8000"
    networks:
      - dev
    depends_on:
      - mongo

  frontend:
    build:
      context: ./CatChat
    expose:
      - "80"  # Фронтенд работает на порту 80 внутри сети
    networks:
      - dev

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - dev

volumes:
  mongo-data: