version: '3'

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"  # Прокидываем 80 порт наружу, чтобы фронтенд был доступен на 80 порту
    volumes:
      - './project-nginx.conf:/etc/nginx/nginx.conf'  # Используем конфигурацию Nginx для проекта
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  frontend:
    build:
      context: ./CatChat
    ports:
      - "80"  # Фронтенд будет доступен на 80 порту внутри контейнера
    networks:
      - dev

  backend:
    build:
      context: ./CatChatBackReborn
    environment:
      - MONGO_URI=mongodb://mongo:27017/chat
    ports:
      - "8000:8000"  # Бэкенд работает на 8000 порту
    networks:
      - dev
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - dev

volumes:
  mongo-data: