version: '3'

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./CatChatBackReborn
    ports:
      - "8000:8000"
    networks:
      - dev

  frontend:
    build:
      context: ./CatChat
    ports:
      - "3000:80"
    networks:
      - dev